FROM centos:latest

RUN sed -i 's|^metalink=|#metalink=|g' /etc/yum.repos.d/*.repo && \
    sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=https://vault.centos.org|g' /etc/yum.repos.d/*.repo && \
    yum -y update && \
    yum -y install yum-utils

CMD ["bash"]
